### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by stark-alex** [stark-alex/beergammon#10]
undo move mid-turn

**Comment by stark-alex** [comment]
closing as won't fix, we're not matt morans here.  once you touch you move

**Comment by dvdvrhs** [comment]
Playing on mobile it's super easy to click the wrong piece.

**Comment by stark-alex** [comment]
agreed, the above was the general concensus when someone mentioned undo...but I think I could get behind putting a piece back where it came from as long as it as hasn't been placed in a new spot.
